go2people/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, handler404, handler500


urlpatterns = [
    path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
'''
This module contains urlpatterns of products app.
'''
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index_view, name='index'),
    path('<slug:product_slug>/', views.product_view, name='product')
]

accounts/models.py
'''
This module contains models represented by:
- Supplier: a class used to represent a Supplier
'''
from django.db import models
from django.contrib.auth.models import User


class Supplier(models.Model):
    '''
    A class used to represent a Supplier
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    thumbnail = models.ImageField(upload_to='profile_images')

    def __str__(self):
        return self.user.username

products/models.py
'''
This module contains models represented by two classes:
- Categroy: a class used to represent a Category
- Product: a class used to represent a Product
'''
from datetime import datetime

from django.db import models
from django.db.models.signals import pre_save

from accounts.models import Supplier
from go2people.utils import unique_slug_generator


SLUG_HELP_TEXT = "The slug must be unique, \
it will be generated automatically if the field is blank."


class Category(models.Model):
    '''
    A class used to represent a Category
    '''
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,
                            blank=True,
                            help_text=SLUG_HELP_TEXT)
    description = models.TextField(blank=True)

    class Meta:
        '''
        This is a Meta class
        '''
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    '''
    A class used to represent a Product
    '''
    supplier = models.ForeignKey(Supplier,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,
                            blank=True,
                            help_text=SLUG_HELP_TEXT)
    categories = models.ManyToManyField(Category)
    description = models.TextField()
    image = models.ImageField(upload_to='products')

    PR = 'PR'
    VMBO = 'VMBO'
    MBO = 'MBO'
    HBO = 'HBO'
    OP = 'OP'
    SCHOOL_TYPE_CHOICES = [
        (PR, 'praktijkonderwijs'),
        (VMBO, 'vmbo'),
        (MBO, 'mbo'),
        (HBO, 'hbo'),
        (OP, 'opleidingsbedrijf')
    ]
    school_type = models.CharField(
        max_length=48,
        choices=SCHOOL_TYPE_CHOICES
    )

    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField('Date published',
                                      default=datetime.now)
    end_at = models.DateTimeField('Publishing end date')

    def __str__(self):
        return self.name

    def is_product_available(self):
        ''' Check if the product is available, so it can be published
        '''
        now = datetime.now()
        return self.created_at <= now <= self.end_at
    is_product_available.boolean = True


def slug_generator(sender, instance, *args, **kwargs):
    ''' Generate a unique slug for a given object
    '''
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(slug_generator, sender=Product)
pre_save.connect(slug_generator, sender=Category)

products/forms.py
'''
This module contains forms:
- CategoryForm: A class represent the form of creating a category
- ProductForm: A class represent the form of creating a product
'''
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Product


CATEGORY_ERROR_SLUG = 'A category with this slug already exists.'

PRODUCT_ERROR_SLUG = 'A product with this slug already exists.'
PRODUCT_ERROR_CATEGORIES = 'One to six categories are allowed.'
PRODUCT_ERROR_PRICE = 'Price must be more than zero (price > 0).'
PRODUCT_ERROR_END_AT = 'Publishing end date cannot be before the date of creation.'

class CategoryForm(ModelForm):
    '''
    A class represent the form of creating a category
    '''
    class Meta:
        model = Product
        fields = '__all__'

    def clean(self):
        ''' A mothod to check the form before saving
        '''
        slug = self.cleaned_data.get('slug')

        error_list = []

        if slug:
            initial_value = self.initial.get('slug')
            qs = self.Meta.model.objects.filter(slug=slug)
            qs = qs.exclude(slug=initial_value)
            if qs.exists():
                error_list.append({'slug': PRODUCT_ERROR_SLUG})

        if error_list:
            raise ValidationError(error_list)


class ProductForm(ModelForm):
    '''
    A class represent the form of creating a product
    '''
    class Meta:
        model = Product
        fields = '__all__'

    def clean(self):
        ''' A mothod to check the form before saving
        '''
        slug = self.cleaned_data.get('slug')
        categories = self.cleaned_data.get('categories')
        price = self.cleaned_data.get('price')
        created_at = self.cleaned_data.get('created_at')
        end_at = self.cleaned_data.get('end_at')

        error_list = []

        # check if the slug already exists
        if slug:
            initial_value = self.initial.get('slug')
            qs = self.Meta.model.objects.filter(slug=slug)
            qs = qs.exclude(slug=initial_value)
            if qs.exists():
                error_list.append({'slug': PRODUCT_ERROR_SLUG})

        # check if the product has one to six categories
        if categories and not 1 <= categories.count() <= 6:
            error_list.append({'categories': PRODUCT_ERROR_CATEGORIES})

        # check if the price is less than 0
        if price and price < 0:
            error_list.append({'price': PRODUCT_ERROR_PRICE})

        # check if end_at is after created_at
        if created_at and end_at and created_at >= end_at:
            error_list.append({'end_at': PRODUCT_ERROR_END_AT})

        if error_list:
            raise ValidationError(error_list)

        return self.cleaned_data

accounts/views.py
'''
This is views
'''
from django.shortcuts import render

# Create your views here.

products/views.py
'''
This module contains views:
- index_view: Returns the view of product list (index).
- product_view: Returns the view of product details (product).
'''
from datetime import datetime
from django.shortcuts import get_object_or_404, render

from products.models import Product


def index_view(request):
    '''
    Returns the view of product list (index)
    '''
    now = datetime.now()
    products = Product.objects.filter(end_at__gt=now, created_at__lt=now)
    context = {
        'page_title': 'List products',
        'title': 'List products',
        'currency': '€',
        'categories': 'Categories',
        'school_type': 'School Type',
        'published_at': 'Date published',
        'end_at': 'Publishing end date',
        'products': products,
    }
    return render(request, 'products/index.html', context)


def product_view(request, product_slug):
    '''
    Returns the view of product details (product)
    '''
    query = Product.objects.filter(slug=product_slug)
    product = get_object_or_404(query)
    context = {
        'page_title': product.name,
        'title': 'Product Details',
        'currency': '€',
        'categories': 'Categories',
        'school_type': 'School Type',
        'published_at': 'Date published',
        'end_at': 'Publishing end date',
        'product': product,
    }

    return render(request, 'products/product.html', context)

products/templates/products/index.html
{% extends 'products/layout.html' %}

{% block title %}
{{page_title}}
{% endblock %}

{% block content %}
<div class="container">
  <h3 class="mt-3 mb-3">{{title}}</h3>
  <div class="row row-cols-1 row-cols-md-3">
    {% for product in products %}
    <div class="col mb-4">
      <div class="card">
        <a href="/products/{{product.slug}}">
          <img src="{{ product.image.url }}" class="card-img-top" alt="#">
        </a>
        <div class="card-body">
          <div class="d-flex justify-content-between mb-2">
            <div class="d-flex">
              <div class="supplier-image" style="background-image:url({{product.supplier.thumbnail.url}});"></div>
              <div class="ml-3">
                <h6 class="m-0">{{product.name}}</h6>
                <span class="m-0 text-secondary">{{product.supplier.user.username}}</span>
              </div>
            </div>
            <span>{{currency}} {{product.price}}</span>
          </div>
          <p class="card-text mb-2">{{product.description|truncatewords:25}}</p>
          <div class="mb-2">
            <h6 class="m-0">{{categories}}</h6>
            {% for category in product.categories.all %}
            <span class="badge badge-pill badge-secondary pt-1 pb-1">{{category}}</span>
            {% endfor %}
          </div>
          <div class="mb-2">
            <h6 class="m-0">{{school_type}}</h6>
            <span>{{product.get_school_type_display}}</span>
          </div>
          <div class="dropdown-divider"></div>
          <div>
            <p class="card-text"><small class="text-muted">{{end_at}}: {{product.end_at}}</small></p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

products/templates/products/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'products/style.css' %}">
  <title>
    {% block title %}{% endblock %}
  </title>
</head>

<body>
  <div>
    {% block content %}
    {% endblock %}
  </div>


  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>

products/templates/products/product.html
{% extends 'products/layout.html' %}

{% block title %}
{{page_title}}
{% endblock %}

{% block content %}
<div class="container" style="max-width: 960px;">
  <h3 class="mt-3 mb-3">{{title}}</h3>
  <div class="d-flex align-items-center mb-3">
    <div class="supplier-image-lg" style="background-image:url({{product.supplier.thumbnail.url}});">
    </div>
    <h5 class="ml-2">{{product.supplier.user.username}}</h5>
  </div>
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="{{ product.image.url }}" class="card-img" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <h6 class="">{{currency}} {{product.price}}</h6>
          <p class="card-text">{{product.description}}</p>
          <div class="mb-2">
            <h6 class="m-0">{{categories}}</h6>
            {% for category in product.categories.all %}
            <span class="badge badge-pill badge-secondary">{{category}}</span>
            {% endfor %}
          </div>
          <div class="mb-2">
            <h6 class="m-0">{{school_type}}</h6>
            <span>{{product.get_school_type_display}}</span>
          </div>
          <div class="dropdown-divider"></div>
          <div>
            <p class="card-text mb-0"><small class="text-muted">{{published_at}}:
                {{product.created_at}}</small></p>
            <p class="card-text"><small class="text-muted">{{end_at}}: {{product.end_at}}</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}